#!/usr/bin/env bash
# ============================================================================
# GitHub -> Termux -> Tailscale -> Windows App
# Chuỗi kết nối từ xa an toàn và linh hoạt
# ============================================================================

clear

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║       GitHub -> Termux -> Tailscale -> Windows App                ║"
echo "║             Chuỗi kết nối môi trường từ xa                        ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# ============================================================================
# PHẦN 1: GitHub - Lưu trữ Repository
# ============================================================================
echo "┌─ [1/4] GITHUB - Lưu trữ Repository ─────────────────────────────────┐"
echo ""
echo "GitHub là nơi lưu trữ và quản lý code của bạn."
echo ""
echo "Các bước:"
echo "  1. Tạo repository trên GitHub"
echo "  2. Tạo GitHub Personal Access Token hoặc dùng SSH key"
echo "  3. Chuẩn bị code sẵn sàng"
echo ""
echo "Lệnh tham khảo:"
echo "  $ git init                          # Tạo repo cục bộ"
echo "  $ git add ."
echo "  $ git commit -m 'Initial commit'"
echo "  $ git remote add origin <repo-url>"
echo "  $ git push -u origin main"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""
sleep 2

# ============================================================================
# PHẦN 2: Termux - Chạy Terminal trên Android
# ============================================================================
echo "┌─ [2/4] TERMUX - Chạy Terminal trên Android ──────────────────────────┐"
echo ""
echo "Termux là terminal emulator giúp bạn chạy Linux trên điện thoại Android."
echo ""
echo "Các bước cài đặt:"
echo "  1. Tải Termux từ F-Droid hoặc Google Play"
echo "  2. Cài đặt các gói cần thiết:"
echo ""
echo "    $ pkg update && pkg upgrade"
echo "    $ pkg install git curl openssh wget vim python clang"
echo "    $ pkg install gh  # GitHub CLI"
echo ""
echo "  3. Tạo SSH key cho GitHub:"
echo ""
echo "    $ ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "    $ cat ~/.ssh/id_ed25519.pub  # Copy vào GitHub Settings"
echo ""
echo "  4. Clone repository:"
echo ""
echo "    $ git clone https://github.com/<username>/<repo>.git"
echo "    $ cd <repo>"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""
sleep 2

# ============================================================================
# PHẦN 3: Tailscale - Mạng Riêng Ảo An Toàn
# ============================================================================
echo "┌─ [3/4] TAILSCALE - Mạng Riêng Ảo An Toàn ───────────────────────────┐"
echo ""
echo "Tailscale tạo một mạng riêng ảo (VPN mesh) giữa các thiết bị của bạn."
echo "Điều này cho phép kết nối an toàn mà không cần mở cổng công khai."
echo ""
echo "Các bước cài đặt:"
echo "  1. Cài Tailscale trên máy chủ / GitHub Codespace:"
echo ""
echo "    $ curl -fsSL https://tailscale.com/install.sh | sh"
echo "    $ sudo tailscale up"
echo ""
echo "  2. Đăng nhập bằng browser hoặc auth key"
echo ""
echo "  3. Cài Tailscale trên máy Windows / thiết bị khác:"
echo "    - Tải từ https://tailscale.com/download"
echo "    - Đăng nhập vào cùng tài khoản"
echo ""
echo "  4. Kiểm tra trạng thái kết nối:"
echo ""
echo "    $ tailscale status"
echo ""
echo "  5. Xem IP Tailscale của bạn:"
echo ""
echo "    $ tailscale ip -4"
echo ""
echo "Lợi ích:"
echo "  - Tất cả thiết bị trong cùng Tailnet có thể giao tiếp"
echo "  - Kết nối được mã hóa tự động"
echo "  - Không cần cấu hình router phức tạp"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""
sleep 2

# ============================================================================
# PHẦN 4: Windows App - Truy Cập Từ Xa Cuối Cùng
# ============================================================================
echo "┌─ [4/4] WINDOWS APP - Truy Cập Từ Xa Cuối Cùng ───────────────────────┐"
echo ""
echo "Windows App là ứng dụng hoặc giao diện trên máy Windows để truy cập"
echo "các ứng dụng và máy chủ từ xa thông qua Tailscale."
echo ""
echo "Các lựa chọn:"
echo "  1. Microsoft Remote Desktop:"
echo "     - Bật trên máy chủ Linux: xrdp, gnome-remote-desktop"
echo "     - Kết nối từ Windows qua IP Tailscale"
echo ""
echo "  2. SSH + Terminal:"
echo "     - Dùng PuTTY, OpenSSH, hoặc Terminal Windows"
echo "     - $ ssh user@<tailscale-ip>"
echo ""
echo "  3. VS Code Remote:"
echo "     - Cài extension 'Remote - SSH'"
echo "     - Kết nối SSH qua Tailscale IP"
echo ""
echo "  4. Ứng dụng Windows tùy chỉnh:"
echo "     - Sử dụng Tailscale SDK để kết nối"
echo ""
echo "Các bước kết nối từ Windows:"
echo "  1. Đảm bảo Windows và máy chủ cùng Tailnet"
echo "  2. Mở Windows App (Remote Desktop / PuTTY / Terminal)"
echo "  3. Kết nối tới IP Tailscale của máy chủ"
echo "  4. Nhập tên đăng nhập và mật khẩu"
echo "  5. Truy cập terminal hoặc desktop từ xa"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""
sleep 2

# ============================================================================
# TÓM TẮT CHUỖI KẾT NỐI
# ============================================================================
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                    TÓM TẮT CHUỖI KẾT NỐI                          ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Quy trình đầy đủ:"
echo ""
echo "  1. GitHub"
echo "     └─ Lưu trữ repository"
echo "        │"
echo "  2. Termux (Android)"
echo "     └─ Chạy terminal từ điện thoại"
echo "        │"
echo "  3. Tailscale"
echo "     └─ Tạo mạng riêng an toàn"
echo "        │"
echo "  4. Windows App"
echo "     └─ Truy cập từ ra qua giao diện Windows"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Mô tả ngắn gọn:"
echo "GitHub lưu repo, Termux chạy terminal, Tailscale tạo mạng riêng,"
echo "Windows App truy cập từ xa."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# LỆNH NHANH THAM KHẢO
# ============================================================================
echo "┌─ LỆNH NHANH THAM KHẢO ──────────────────────────────────────────────┐"
echo ""
echo "GitHub:"
echo "  $ git clone <repo-url>"
echo "  $ git add ."
echo "  $ git commit -m 'message'"
echo "  $ git push"
echo ""
echo "Termux:"
echo "  $ pkg update && pkg upgrade"
echo "  $ pkg install git openssh gh"
echo "  $ ssh-keygen -t ed25519 -C 'email@example.com'"
echo ""
echo "Tailscale:"
echo "  $ curl -fsSL https://tailscale.com/install.sh | sh"
echo "  $ sudo tailscale up"
echo "  $ tailscale status"
echo "  $ tailscale ip -4"
echo ""
echo "Windows:"
echo "  $ ssh user@<tailscale-ip>"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""

# ============================================================================
# LƯU Ý BẢOẠ MẬT
# ============================================================================
echo "┌─ LƯU Ý BẢOẠ MẬT ────────────────────────────────────────────────────┐"
echo ""
echo "⚠️  Bảo vệ SSH Private Key - KHÔNG chia sẻ"
echo "⚠️  Bảo vệ GitHub Token - KHÔNG commit vào repository"
echo "⚠️  Tailscale Auth Key - CHỈ dùng một lần"
echo "⚠️  Luôn dùng HTTPS hoặc SSH cho git push"
echo "⚠️  Kiểm tra permissions trên máy chủ từ xa"
echo ""
echo "└──────────────────────────────────────────────────────────────────────┘"
echo ""

# ============================================================================
# KẾT THÚC
# ============================================================================
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                     ✓ CHUỖI KẾT NỐI HOÀN CHỈNH                   ║"
echo "║                                                                    ║"
echo "║      GitHub → Termux → Tailscale → Windows App                   ║"
echo "║                                                                    ║"
echo "║  Bạn đã có hướng dẫn đầy đủ để triển khai hệ thống từ xa an toàn ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📌 Tham khảo thêm:"
echo "   - https://github.com"
echo "   - https://termux.dev"
echo "   - https://tailscale.com"
echo ""
echo "✅ Script kết thúc. Chúc bạn thành công!"
echo ""
