#!/usr/bin/env bash
# GitHub -> Termux -> Tailscale -> Windows App
# Chuỗi kết nối từ xa đầy đủ và rõ ràng

clear

echo "====================================================="
echo "GitHub -> Termux -> Tailscale -> Windows App"
echo "====================================================="
echo ""
echo "1) GitHub"
echo "   - GitHub là nơi lưu trữ repository và mã nguồn."
echo "   - Bạn tạo repo, push code, và quản lý các dự án ở đây."
echo "   Ví dụ:"
echo "   git clone <repo-url>"
echo ""
echo "2) Termux"
echo "   - Termux chạy terminal trên Android, cho phép bạn làm việc từ điện thoại."
echo "   - Bạn cài git, gh, openssh và có thể clone repo từ GitHub."
echo "   Ví dụ:"
echo "   pkg update && pkg upgrade"
echo "   pkg install git gh openssh"
echo "   git clone <repo-url>"
echo ""
echo "3) Tailscale"
echo "   - Tailscale tạo mạng riêng ảo (Tailnet) giữa các thiết bị."
echo "   - Nó giúp thiết bị Windows, máy chủ và Termux kết nối an toàn mà không cần mở cổng ra Internet."
echo "   Ví dụ:"
echo "   curl -fsSL https://tailscale.com/install.sh | sh"
echo "   sudo tailscale up"
echo "   tailscale status"
echo ""
echo "4) Windows App"
echo "   - Windows App là điểm cuối cuối cùng để truy cập từ xa."
echo "   - Sau khi các thiết bị cùng nằm trong Tailscale, bạn mở Windows App hoặc Remote Desktop để truy cập."
echo ""
echo "====================================================="
echo "Chuỗi kết nối đúng: GitHub -> Termux -> Tailscale -> Windows App"
echo "====================================================="
echo ""
echo "Ví dụ quá trình làm việc:"
echo "- Tạo repo trên GitHub"
echo "- Clone repo bằng Termux"
echo "- Kết nối Termux và máy Windows qua Tailscale"
echo "- Mở Windows App để truy cập từ xa"
echo ""
echo "Lưu ý:"
echo "- Bảo mật SSH key và GitHub token"
echo "- Không share auth key Tailscale"
echo "- Dùng cùng một tài khoản Tailscale trên các thiết bị"
echo ""
echo "Kết luận: GitHub lưu code, Termux chạy terminal, Tailscale nối mạng, Windows App truy cập từ xa."
